### ISSUE TITLE
No full screen button

### ISSUE THREAD

**Issue by WWH-exe** [MaVeN-LLC/RVX#2] opened 2024-03-30 22:15 UTC
The full screen button is not appearing on the corner of video player

Using Galaxy note 9 with android 10

**Comment by Bouab-Ahmed** [comment] 2024-03-31 10:11
Facing the same probelm
Using Redmi note 8

**Comment by TBNRDev** [comment] 2024-04-02 07:41
did you guys use the patch.txt

**Comment by WWH-exe** [comment] 2024-04-02 08:20
Yes I did

**Comment by TBNRDev** [comment] 2024-04-09 11:51
Duplicate of #6

**Closed by TBNRDev** 2024-04-09 11:51 UTC
